version: '3'
services:
    db:
        image: postgres:9.6.3-alpine
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_PASSWORD=TESTtest
            - POSTGRES_DB=allo
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - ./.volumes/db/data/:/var/lib/postgresql/data/pgdata/
    app:
        build: ./src/
        depends_on:
            - db
        volumes:
            - ./src/:/usr/src/app/